const scenes=[...document.querySelectorAll('.scene')];
const fundingDate=document.createElement('p');fundingDate.className='caption';fundingDate.textContent='Current NSF target: November 16, 2026. Submissions are accepted at any time, but later proposals may enter the next fiscal year. A full 12 week pilot from late September finishes after this target; discuss readiness and timing with the program officer.';document.querySelector('.fundingpanel').append(fundingDate);
const nav=document.getElementById('nav');
let chapter=0;
nav.innerHTML=scenes.map((s,i)=>`<button data-go="${i}"><span>${String(i+1).padStart(2,'0')}</span>${s.dataset.title}</button>`).join('');
function go(i){chapter=Math.max(0,Math.min(scenes.length-1,i));scenes.forEach((s,j)=>s.classList.toggle('active',j===chapter));[...nav.children].forEach((b,j)=>{b.classList.toggle('active',j===chapter);b.setAttribute('aria-current',j===chapter?'step':'false')});document.getElementById('chapterCount').textContent=String(chapter+1).padStart(2,'0')+' / 08';document.getElementById('prev').disabled=chapter===0;document.getElementById('next').disabled=chapter===7;history.replaceState(null,'','#'+chapter);window.scrollTo(0,0)}
document.querySelectorAll('[data-go]').forEach(b=>b.addEventListener('click',()=>go(Number(b.dataset.go))));
document.getElementById('prev').onclick=()=>go(chapter-1);document.getElementById('next').onclick=()=>go(chapter+1);
document.addEventListener('keydown',e=>{if(['INPUT','TEXTAREA','SELECT'].includes(e.target.tagName))return;if(e.key==='ArrowRight')go(chapter+1);if(e.key==='ArrowLeft')go(chapter-1)});
document.getElementById('notesToggle').onclick=()=>{document.body.classList.toggle('showNotes');document.getElementById('notesToggle').setAttribute('aria-pressed',document.body.classList.contains('showNotes'))};
document.getElementById('fullscreen').onclick=async()=>{try{if(!document.fullscreenElement)await document.documentElement.requestFullscreen();else await document.exitFullscreen()}catch{document.getElementById('fullscreen').textContent='Use browser full screen'}};
let revealed=false;const slider=document.getElementById('drift');
function draw(){const d=Number(slider.value),px=v=>90+(v+2)*95,py=v=>290-v*220;let curve='';for(let v=-2;v<=4.01;v+=.025){const val=Math.exp(-.5*((v-d)/.5)**2);curve+=(curve?'L':'M')+px(v).toFixed(1)+' '+py(val).toFixed(1)}let ticks='';for(let n=-2;n<=4;n++)ticks+=`<line x1="${px(n)}" x2="${px(n)}" y1="40" y2="290" stroke="#253746"/><text x="${px(n)}" y="320" text-anchor="middle" fill="#9badba" font-size="12">${n}σ</text>`;document.getElementById('experimentPlot').innerHTML=`${ticks}<path d="${curve}L${px(4)} 290L${px(-2)} 290Z" fill="#55e3c218"/><path d="${curve}" fill="none" stroke="#55e3c2" stroke-width="3"/><line x1="${px(d)}" x2="${px(d)}" y1="70" y2="290" stroke="#55e3c2" stroke-dasharray="3 5"/><text x="${px(d)}" y="48" text-anchor="middle" fill="#55e3c2" font-size="13">Inferred parameter</text>${revealed?`<line x1="${px(0)}" x2="${px(0)}" y1="30" y2="290" stroke="#ffb67c" stroke-width="2"/><text x="${px(0)}" y="20" text-anchor="middle" fill="#ffb67c" font-size="12">Known truth</text>`:''}<text x="375" y="355" text-anchor="middle" fill="#9badba" font-size="11">Parameter displacement / fixed reference standard deviation</text>`;document.getElementById('driftValue').textContent=d.toFixed(1)+'σ';document.getElementById('estimate').textContent='+'+d.toFixed(1)+'σ';document.getElementById('bias').textContent=revealed?d.toFixed(1)+'σ':'Sealed';document.getElementById('bias').style.color=revealed?'var(--amber)':'var(--muted)'}
slider.addEventListener('input',draw);document.getElementById('reveal').onclick=()=>{revealed=!revealed;document.getElementById('reveal').textContent=revealed?'Seal evaluator truth':'Reveal evaluator truth';document.getElementById('revealText').textContent=revealed?'The fit did not warn us. A trustworthy analyst needs additional information, or an explicit statement of nonidentifiability.':'The analyst sees the data and fit. The evaluator knows what was injected.';draw()};draw();
const methods=[['The baseline is a research result','Can established tests already solve the problem?','Freeze the reference pipeline and calibrate its diagnostics on clean simulations. If a simpler method wins at matched cost, keep it.'],['Reasoning must add measurable value','Does an agent choose better diagnostic tests?','Give a single agent approved analysis tools, a resource ceiling and no evaluator truth. Freeze its report before revealing labels. Measure detection, attribution, uncertainty and cost.'],['Representation is an experimental variable','Does learned structure expose a missed failure?','Compare specialist models and available foundation model representations with identical data access. Validate calibration and survey transfer separately. A large model is optional.'],['More agents is a hypothesis','Does coordination improve reliability per unit cost?','Separate investigator, critic and verifier roles. Compare with the single agent at the same total resource budget. Correlated errors, duplicated work and persuasive consensus are failure modes, not safeguards.']];
document.querySelectorAll('[data-method]').forEach(b=>b.onclick=()=>{document.querySelectorAll('[data-method]').forEach(x=>x.classList.toggle('selected',x===b));const m=methods[+b.dataset.method];['methodTag','methodTitle','methodText'].forEach((id,i)=>document.getElementById(id).textContent=m[i])});
const phases=[['Weeks 1 to 4','Reproduce the baseline','Freeze one survey configuration, one inference target and one injection family.','SNANA configurations and permitted simulation products. Existing pipeline outputs only after provenance review.','A reproducible run, clean controls, a versioned injection manifest and measured runtime.','Can an independent rerun reproduce the baseline and the intended injection effect?','Domain scientist + research software engineer. Existing CPU allocation if available.'],['Weeks 5 to 12','Run the blinded pilot','Test scientific judgment before scaling the infrastructure.','Fresh simulated realizations with clean and perturbed cases. Choose sample size from desired power and uncertainty.','Baseline versus single agent comparison, leakage audit, cost record and a preliminary failure map.','Are false alarms controlled and results repeatable? Is the injection identifiable from the allowed evidence?','Scientist, engineer and independent evaluator. Cap model spend and queue usage.'],['Months 4 to 9','Release benchmark v1','Turn a demonstration into a reusable scientific instrument.','Multiple SN systematic families with held out seeds and combinations.','Documented protocol, uncertainty intervals, ablations, reproducible artifacts and a research paper.','Does the benchmark expose a consequential limitation or improvement beyond established diagnostics?','Costed research effort, student participation and maintained software. Funding required for sustained work.'],['Months 10 to 18','Add a second probe','Test whether the evaluation contract survives a change of physics.','An agreed lensing and clustering pipeline, its likelihood, covariances and permitted simulated catalogs.','A 3×2pt adapter with one controlled nuisance family, plus a transfer study.','Can the second probe be evaluated without rewriting the core or concealing probe specific assumptions?','A probe specialist joins. Compute and access negotiated before integration.'],['Months 19 to 36','Stress test joint inference','Study shared nuisance errors and misleading apparent consistency.','SN and second probe products with an explicit joint likelihood and shared nuisance model.','Joint failure atlas, external replication and a practical adoption path.','Are correlations modeled correctly, and do external users obtain reproducible scientific value?','Dedicated maintenance, independent validation and collaboration agreements. CMB and other sciences remain future options.']];
document.getElementById('timeline').innerHTML=phases.map((p,i)=>`<button data-phase="${i}">${p[0]}<small>${p[1]}</small></button>`).join('');
function phase(i){const p=phases[i];['phaseTime','phaseTitle','phaseSummary','phaseData','phaseOutput','phaseGate','phasePeople'].forEach((id,j)=>document.getElementById(id).textContent=p[j]);document.querySelectorAll('[data-phase]').forEach(b=>b.classList.toggle('active',+b.dataset.phase===i));document.getElementById('progress').style.width=[3,8,25,50,100][i]+'%'}document.querySelectorAll('[data-phase]').forEach(b=>b.onclick=()=>phase(+b.dataset.phase));phase(0);
const probes=[['INITIAL SCOPE','Supernova cosmology','Inject calibration, selection, dust, host or contamination effects and propagate through the analysis to the chosen cosmological parameters. Begin with one well understood family.','Simulated truth is conditional on the simulator. Real observations require external checks and cannot supply an exact cosmological answer key.'],['CONDITIONAL EXPANSION','Lensing and clustering','Add an adapter for a controlled photo z or shear calibration perturbation. Carry survey masks, selections, likelihood assumptions and covariance explicitly.','An expert in the second probe must own the physical validity of the injection and inference configuration.'],['RESEARCH FRONTIER','Shared failure modes','A shared nuisance error can move two probes together. Agreement does not by itself establish accuracy. Evaluate the joint likelihood and correlated systematics.','Do not combine marginal posteriors as if the probes and their nuisance parameters were independent.'],['FUTURE OPTION','Beyond the first proposal','CMB, gravitational waves or another scientific domain can use the evaluation pattern when trustworthy forward models, interpretable faults and suitable metrics exist.','Transfer is a hypothesis to test. Domain validation and a new partner are required; the astronomical model weights need not transfer.']];
document.querySelectorAll('[data-probe]').forEach(b=>b.onclick=()=>{document.querySelectorAll('[data-probe]').forEach(x=>x.classList.toggle('selected',x===b));const p=probes[+b.dataset.probe];['probeTag','probeTitle','probeText','probeCaution'].forEach((id,i)=>document.getElementById(id).textContent=p[i])});document.querySelector('[data-probe="0"]').click();go(Number(location.hash.slice(1))||0);
